#spring.application.name=APiRest

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DCN}

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
